'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resources_zh_HanFurry
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FurryArtStudio.Resources.zh-HanFurry", GetType(Resources_zh_HanFurry).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 确定(&amp;O) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_BtnOK() As String
            Get
                Return ResourceManager.GetString("About_BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 猫猫 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_LinkGitHub() As String
            Get
                Return ResourceManager.GetString("About_LinkGitHub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 许可证 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_LinkLicense() As String
            Get
                Return ResourceManager.GetString("About_LinkLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 隐私政策 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_LinkPrivacy() As String
            Get
                Return ResourceManager.GetString("About_LinkPrivacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户协议 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_LinkUserAgreement() As String
            Get
                Return ResourceManager.GetString("About_LinkUserAgreement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 官网 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_LinkWebSite() As String
            Get
                Return ResourceManager.GetString("About_LinkWebSite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关于 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About_Title() As String
            Get
                Return ResourceManager.GetString("About_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 提取结果 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ColorDialog_Title() As String
            Get
                Return ResourceManager.GetString("ColorDialog_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 添加(&amp;A)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnAddItem() As String
            Get
                Return ResourceManager.GetString("Edit_BtnAddItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 取消(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnCancel() As String
            Get
                Return ResourceManager.GetString("Edit_BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 删除(&amp;D)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnDel() As String
            Get
                Return ResourceManager.GetString("Edit_BtnDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 确定(&amp;O) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnOK() As String
            Get
                Return ResourceManager.GetString("Edit_BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 保存(&amp;S) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnSave() As String
            Get
                Return ResourceManager.GetString("Edit_BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 设为封面(&amp;P) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_BtnSetPreview() As String
            Get
                Return ResourceManager.GetString("Edit_BtnSetPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 编辑稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_EditTitle() As String
            Get
                Return ResourceManager.GetString("Edit_EditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 作者: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblAuthor() As String
            Get
                Return ResourceManager.GetString("Edit_LblAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 角色: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblCharacters() As String
            Get
                Return ResourceManager.GetString("Edit_LblCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 创作时间: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblCreate() As String
            Get
                Return ResourceManager.GetString("Edit_LblCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导入时间: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblImport() As String
            Get
                Return ResourceManager.GetString("Edit_LblImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 备注: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblNotes() As String
            Get
                Return ResourceManager.GetString("Edit_LblNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 标签: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblTags() As String
            Get
                Return ResourceManager.GetString("Edit_LblTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 标题: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblTitle() As String
            Get
                Return ResourceManager.GetString("Edit_LblTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 更新时间: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_LblUpdate() As String
            Get
                Return ResourceManager.GetString("Edit_LblUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Edit_NewTitle() As String
            Get
                Return ResourceManager.GetString("Edit_NewTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 FurryArtStudio 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FurryArtStudio() As String
            Get
                Return ResourceManager.GetString("FurryArtStudio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 克隆稿件库 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Input_CloneLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_CloneLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建稿件库 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Input_NewLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_NewLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重命名稿件库 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Input_RenameLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_RenameLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} 的副本 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Input_TxtClone() As String
            Get
                Return ResourceManager.GetString("Input_TxtClone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新稿件库 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Input_TxtNewLib() As String
            Get
                Return ResourceManager.GetString("Input_TxtNewLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CSV文件(*.csv)|*.csv|所有文件(*.*)|*.* 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_FileFilterCSV() As String
            Get
                Return ResourceManager.GetString("Main_FileFilterCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 角色: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblCharacter() As String
            Get
                Return ResourceManager.GetString("Main_LblCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件库: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblLibName() As String
            Get
                Return ResourceManager.GetString("Main_LblLibName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} 个稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblMs() As String
            Get
                Return ResourceManager.GetString("Main_LblMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;无稿件库&gt; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNoLib() As String
            Get
                Return ResourceManager.GetString("Main_LblNoLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 0 个稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNoMs() As String
            Get
                Return ResourceManager.GetString("Main_LblNoMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 页码: 0/0 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNoPage() As String
            Get
                Return ResourceManager.GetString("Main_LblNoPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 请选择一个项目 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNoSelect() As String
            Get
                Return ResourceManager.GetString("Main_LblNoSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 存储: 0B (0个文件) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNoStorage() As String
            Get
                Return ResourceManager.GetString("Main_LblNoStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 备注: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblNotes() As String
            Get
                Return ResourceManager.GetString("Main_LblNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 页码: {0}/{1} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblPage() As String
            Get
                Return ResourceManager.GetString("Main_LblPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 页码: 1/{0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblPage1() As String
            Get
                Return ResourceManager.GetString("Main_LblPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已搜到 {0} 个稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblSearchedMs() As String
            Get
                Return ResourceManager.GetString("Main_LblSearchedMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已选: {0}/{1} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblSelectMs() As String
            Get
                Return ResourceManager.GetString("Main_LblSelectMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已选: 1/{0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblSelectMs1() As String
            Get
                Return ResourceManager.GetString("Main_LblSelectMs1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 存储: {0} ({1} 个文件) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblStorage() As String
            Get
                Return ResourceManager.GetString("Main_LblStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 标签: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblTags() As String
            Get
                Return ResourceManager.GetString("Main_LblTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已选择 {0} 个项目 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_LblTitleSelect() As String
            Get
                Return ResourceManager.GetString("Main_LblTitleSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Apache License 2.0 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrLicense() As String
            Get
                Return ResourceManager.GetString("Main_StrLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 操作已被用户取消 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrOperationCancelled() As String
            Get
                Return ResourceManager.GetString("Main_StrOperationCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 隐私政策 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPrivacy() As String
            Get
                Return ResourceManager.GetString("Main_StrPrivacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件库: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPropLib() As String
            Get
                Return ResourceManager.GetString("Main_StrPropLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 库目录: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPropLibPath() As String
            Get
                Return ResourceManager.GetString("Main_StrPropLibPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件数: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPropMsCount() As String
            Get
                Return ResourceManager.GetString("Main_StrPropMsCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 当前时间: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPropNowTime() As String
            Get
                Return ResourceManager.GetString("Main_StrPropNowTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 存储: {0} 文件: {1} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrPropStorage() As String
            Get
                Return ResourceManager.GetString("Main_StrPropStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户协议 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrTerms() As String
            Get
                Return ResourceManager.GetString("Main_StrTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新增功能 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Main_StrWhatsNew() As String
            Get
                Return ResourceManager.GetString("Main_StrWhatsNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关于(&amp;A)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_About() As String
            Get
                Return ResourceManager.GetString("Mnu_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 高级搜索(&amp;D)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_AdvancedSearch() As String
            Get
                Return ResourceManager.GetString("Mnu_AdvancedSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 窗口置顶(&amp;T) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_AlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("Mnu_AlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 检查更新(&amp;U) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_CheckUpdate() As String
            Get
                Return ResourceManager.GetString("Mnu_CheckUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 克隆(&amp;L)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Clone() As String
            Get
                Return ResourceManager.GetString("Mnu_Clone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关闭(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Close() As String
            Get
                Return ResourceManager.GetString("Mnu_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 复制文件夹(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Copy() As String
            Get
                Return ResourceManager.GetString("Mnu_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 复制目录路径(&amp;T) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_CopyPath() As String
            Get
                Return ResourceManager.GetString("Mnu_CopyPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 当前库(&amp;U) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_CurrentLib() As String
            Get
                Return ResourceManager.GetString("Mnu_CurrentLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 删除(&amp;D)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Delete() As String
            Get
                Return ResourceManager.GetString("Mnu_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 开发者工具(&amp;D)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_DevTools() As String
            Get
                Return ResourceManager.GetString("Mnu_DevTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 捐赠(&amp;D) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Donate() As String
            Get
                Return ResourceManager.GetString("Mnu_Donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 编辑(&amp;E)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Edit() As String
            Get
                Return ResourceManager.GetString("Mnu_Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 退出(&amp;X) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Exit() As String
            Get
                Return ResourceManager.GetString("Mnu_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导出(&amp;E)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Export() As String
            Get
                Return ResourceManager.GetString("Mnu_Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导出为 CSV 文件(&amp;V)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_ExportCSV() As String
            Get
                Return ResourceManager.GetString("Mnu_ExportCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导出(&amp;X)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_ExportMs() As String
            Get
                Return ResourceManager.GetString("Mnu_ExportMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文件(&amp;F) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_File() As String
            Get
                Return ResourceManager.GetString("Mnu_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 统计信息(&amp;S)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_FormProperties() As String
            Get
                Return ResourceManager.GetString("Mnu_FormProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;GitHub 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_GitHub() As String
            Get
                Return ResourceManager.GetString("Mnu_GitHub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 帮助(&amp;H) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Help() As String
            Get
                Return ResourceManager.GetString("Mnu_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 导入(&amp;I)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Import() As String
            Get
                Return ResourceManager.GetString("Mnu_Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件库(&amp;L) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Lib() As String
            Get
                Return ResourceManager.GetString("Mnu_Lib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 许可证(&amp;L)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_License() As String
            Get
                Return ResourceManager.GetString("Mnu_License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件(&amp;M) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Ms() As String
            Get
                Return ResourceManager.GetString("Mnu_Ms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建(&amp;N)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_New() As String
            Get
                Return ResourceManager.GetString("Mnu_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建稿件(&amp;N)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_NewMs() As String
            Get
                Return ResourceManager.GetString("Mnu_NewMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 下一页(&amp;N) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Next() As String
            Get
                Return ResourceManager.GetString("Mnu_Next", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打开目录(&amp;O) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_OpenPath() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 在此处打开终端(&amp;T) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_OpenTerminal() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenTerminal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 选项(&amp;O)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Options() As String
            Get
                Return ResourceManager.GetString("Mnu_Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 幻灯片放映(&amp;P) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Play() As String
            Get
                Return ResourceManager.GetString("Mnu_Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上一页(&amp;E) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Prev() As String
            Get
                Return ResourceManager.GetString("Mnu_Prev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印(&amp;P)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Print() As String
            Get
                Return ResourceManager.GetString("Mnu_Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 隐私政策(&amp;P)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Privacy() As String
            Get
                Return ResourceManager.GetString("Mnu_Privacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 统计信息(&amp;S)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Properties() As String
            Get
                Return ResourceManager.GetString("Mnu_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 刷新(&amp;R) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Refresh() As String
            Get
                Return ResourceManager.GetString("Mnu_Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重命名(&amp;M)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Rename() As String
            Get
                Return ResourceManager.GetString("Mnu_Rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 以管理员身份重启(&amp;R) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_RunAsElevated() As String
            Get
                Return ResourceManager.GetString("Mnu_RunAsElevated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 搜索(&amp;F) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Search() As String
            Get
                Return ResourceManager.GetString("Mnu_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 全选(&amp;A) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_SelectAll() As String
            Get
                Return ResourceManager.GetString("Mnu_SelectAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 反选(&amp;R) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_SelectReverse() As String
            Get
                Return ResourceManager.GetString("Mnu_SelectReverse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用户协议(&amp;T)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Terms() As String
            Get
                Return ResourceManager.GetString("Mnu_Terms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 教程(&amp;T) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Tutorial() As String
            Get
                Return ResourceManager.GetString("Mnu_Tutorial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 预览(&amp;V) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_View() As String
            Get
                Return ResourceManager.GetString("Mnu_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 视图(&amp;V) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Views() As String
            Get
                Return ResourceManager.GetString("Mnu_Views", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 官网(&amp;W) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_Website() As String
            Get
                Return ResourceManager.GetString("Mnu_Website", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新增功能(&amp;W) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Mnu_WhatsNew() As String
            Get
                Return ResourceManager.GetString("Mnu_WhatsNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 此操作不可逆! 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_CannotBeIrreversible() As String
            Get
                Return ResourceManager.GetString("Msg_CannotBeIrreversible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在检查更新... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_CheckingUpdate() As String
            Get
                Return ResourceManager.GetString("Msg_CheckingUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 检查更新失败 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_CheckUpdateFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CheckUpdateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 复制详细信息(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_CopyDetails() As String
            Get
                Return ResourceManager.GetString("Msg_CopyDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 创建失败 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_CreateFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你希望将稿件库 {0} 移到回收站吗? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteLib() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 移到回收站 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteLibConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLibConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你希望永久删除稿件库 {0} 吗?  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteLibPermanently() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLibPermanently", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 确实要将这 {0} 项放入回收站吗? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteMs() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 删除稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteMsConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ...等 {0} 个项目 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteMsCount() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 确实要永久性的删除 {0} 项稿件吗? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteMsPermanently() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsPermanently", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 永久删除稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DeleteMsPermanentlyConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsPermanentlyConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 下载新版本 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_DownloadNewVer() As String
            Get
                Return ResourceManager.GetString("Msg_DownloadNewVer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 权限提升失败 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_ElevatedFailed() As String
            Get
                Return ResourceManager.GetString("Msg_ElevatedFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 我知道我在做什么! 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_IKnowWhatIamDoing() As String
            Get
                Return ResourceManager.GetString("Msg_IKnowWhatIamDoing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无法加载图片: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_ImageLoadFailed() As String
            Get
                Return ResourceManager.GetString("Msg_ImageLoadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 稿件库删除失败 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_LibDeleteFailed() As String
            Get
                Return ResourceManager.GetString("Msg_LibDeleteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 您将同时打开 {0} 个文件夹, 确定要继续吗? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_MultiFolderOpen() As String
            Get
                Return ResourceManager.GetString("Msg_MultiFolderOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 发现新版本: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_NewVerFound() As String
            Get
                Return ResourceManager.GetString("Msg_NewVerFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 当前稿件没有图片文件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_NoImg() As String
            Get
                Return ResourceManager.GetString("Msg_NoImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 没有找到可打印的图片文件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_NoPrintFile() As String
            Get
                Return ResourceManager.GetString("Msg_NoPrintFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印时出错: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_PrintFailed() As String
            Get
                Return ResourceManager.GetString("Msg_PrintFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 角色: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsCharacters() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 创作时间: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsCreate() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 入库时间: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsImport() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ## 稿件信息: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsInfo() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 备注: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsNotes() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 当前时间: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsNow() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 *由 FurryArtStudio 提供技术支持* 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsSupportByFAS() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsSupportByFAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 标签: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsTags() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ### 标题: {0} - {1} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsTitle() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 总计 {0} 个稿件 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsTotal() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - 更新时间: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsUpdate() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - UUID: {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_StrMsUUID() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsUUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 命令提示符启动失败 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_TerminalFailed() As String
            Get
                Return ResourceManager.GetString("Msg_TerminalFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 当前已是最新版本 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Msg_UptoDate() As String
            Get
                Return ResourceManager.GetString("Msg_UptoDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 取消(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_BtnCancel() As String
            Get
                Return ResourceManager.GetString("Print_BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印(&amp;P) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_BtnPrint() As String
            Get
                Return ResourceManager.GetString("Print_BtnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 横向 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_Horizontal() As String
            Get
                Return ResourceManager.GetString("Print_Horizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 下边距: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblBottom() As String
            Get
                Return ResourceManager.GetString("Print_LblBottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 份数: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblCount() As String
            Get
                Return ResourceManager.GetString("Print_LblCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 左边距: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblLeft() As String
            Get
                Return ResourceManager.GetString("Print_LblLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 纸张:  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblPaper() As String
            Get
                Return ResourceManager.GetString("Print_LblPaper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印机: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblPrinter() As String
            Get
                Return ResourceManager.GetString("Print_LblPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 右边距: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblRight() As String
            Get
                Return ResourceManager.GetString("Print_LblRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上边距: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblTop() As String
            Get
                Return ResourceManager.GetString("Print_LblTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 布局: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_LblType() As String
            Get
                Return ResourceManager.GetString("Print_LblType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印机管理(&amp;M) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_PrinterManager() As String
            Get
                Return ResourceManager.GetString("Print_PrinterManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 打印 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_Title() As String
            Get
                Return ResourceManager.GetString("Print_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 竖向 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Print_Vertical() As String
            Get
                Return ResourceManager.GetString("Print_Vertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关闭(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Prop_BtnClose() As String
            Get
                Return ResourceManager.GetString("Prop_BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在克隆稿件库... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Cloning() As String
            Get
                Return ResourceManager.GetString("Stat_Cloning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在关闭稿件库... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Closing() As String
            Get
                Return ResourceManager.GetString("Stat_Closing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在创建稿件库... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_CreatingLib() As String
            Get
                Return ResourceManager.GetString("Stat_CreatingLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在删除稿件库... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_DeletingLib() As String
            Get
                Return ResourceManager.GetString("Stat_DeletingLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在删除稿件... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_DeletingMs() As String
            Get
                Return ResourceManager.GetString("Stat_DeletingMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在编辑稿件... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_EditMs() As String
            Get
                Return ResourceManager.GetString("Stat_EditMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在导出为CSV... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_ExportCSV() As String
            Get
                Return ResourceManager.GetString("Stat_ExportCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在初始化... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Init() As String
            Get
                Return ResourceManager.GetString("Stat_Init", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在载入数据... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Loading() As String
            Get
                Return ResourceManager.GetString("Stat_Loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在新建稿件... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_NewMs() As String
            Get
                Return ResourceManager.GetString("Stat_NewMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在设置首选项... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_OpenProp() As String
            Get
                Return ResourceManager.GetString("Stat_OpenProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在初始化打印... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_PreparePrint() As String
            Get
                Return ResourceManager.GetString("Stat_PreparePrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在打印... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Printing() As String
            Get
                Return ResourceManager.GetString("Stat_Printing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 就绪 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Ready() As String
            Get
                Return ResourceManager.GetString("Stat_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在重命名稿件库... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Renaming() As String
            Get
                Return ResourceManager.GetString("Stat_Renaming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在搜索... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Stat_Searching() As String
            Get
                Return ResourceManager.GetString("Stat_Searching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 复制(&amp;C) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Copy() As String
            Get
                Return ResourceManager.GetString("View_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 提取(&amp;E) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Extract() As String
            Get
                Return ResourceManager.GetString("View_Extract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文件属性(&amp;R) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_FileProperties() As String
            Get
                Return ResourceManager.GetString("View_FileProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 全屏(&amp;F) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Fullscreen() As String
            Get
                Return ResourceManager.GetString("View_Fullscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 帮助(&amp;H)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Help() As String
            Get
                Return ResourceManager.GetString("View_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 详情(&amp;I)... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Info() As String
            Get
                Return ResourceManager.GetString("View_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;K-Means聚类 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_KMeansCluster() As String
            Get
                Return ResourceManager.GetString("View_KMeansCluster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 中位切分(&amp;M) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_MedianCut() As String
            Get
                Return ResourceManager.GetString("View_MedianCut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 下一张(&amp;N) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_NextImg() As String
            Get
                Return ResourceManager.GetString("View_NextImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 下一稿件(&amp;E) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_NextMs() As String
            Get
                Return ResourceManager.GetString("View_NextMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 八叉树(&amp;O) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_Octree() As String
            Get
                Return ResourceManager.GetString("View_Octree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上一张(&amp;P) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_PreviousImg() As String
            Get
                Return ResourceManager.GetString("View_PreviousImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 上一稿件(&amp;R) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property View_PreviousMs() As String
            Get
                Return ResourceManager.GetString("View_PreviousMs", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
